cmd: mbed compile --profile develop.json
name: compile
targets:
  flash:
    cmd: mbed compile --profile develop.json --flash

  jetson:
    cmd: mbed compile --profile develop.json && scp ./BUILD/NUCLEO_L432KC/GCC_ARM-DEVELOP/controller.bin nvidia@172.86.160.9

  compile-old:
    cmd: mbed compile

errorMatch:
  - "\\[ERROR\\]\\s(?<file>([A-Za-z]:[\\/])?[^:\\n]+):(?<line>\\d+):(?<col>\\d+):\\s*(fatal error|error):\\s*(?<message>.+)"

warningMatch:
  - "\\[WARNING\\]\\s(?<file>([A-Za-z]:[\\/])?[^:\\n]+):(?<line>\\d+):(?<col>\\d+):\\s*(warning):\\s*(?<message>.+)"
  
